WebUygulamaProje1/Models/KitapTuru.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebUygulamaProje1.Models
{
    public class KitapTuru
    {
        [Key] // Primary key anlamına geliyor.
        public int Id { get; set; }

        [Required(ErrorMessage = "Kitap Türü Adı Boş Bırakılmaz!")] // Not Null Anlamına Geliyor.
        [MaxLength(25)]
        [DisplayName("Kitap Türü Adı")]
        public string Ad { get; set; }

        

    }
}

WebUygulamaProje1/Controllers/KitapTuruController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebUygulamaProje1.Models;
using WebUygulamaProje1.Utility;

namespace WebUygulamaProje1.Controllers
{
    [Authorize(Roles = UserRoles.Role_Admin)]
    public class KitapTuruController : Controller
    {
        private readonly IKitapTuruRepository _kitapTuruRepository;
        public KitapTuruController(IKitapTuruRepository context)
        {
            _kitapTuruRepository = context;
        }
        public IActionResult Index()
        {
            List<KitapTuru> objKitapTuruList = _kitapTuruRepository.GetAll().ToList();

            return View(objKitapTuruList);
        }

        public IActionResult Ekle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Ekle(KitapTuru kitapTuru)
        {
            if (ModelState.IsValid)
            {
                _kitapTuruRepository.Ekle(kitapTuru);
                _kitapTuruRepository.Kaydet(); //SaveChanges yapmazsanız bilgiler veritabanına eklenmez.
                TempData["basarili"] = "Kitap Türü Başarılıyla Oluşturuldu.";
                return RedirectToAction("Index");
            }
            return View();
        }


        public IActionResult Guncelle(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            KitapTuru? kitapTuruVt = _kitapTuruRepository.Get(u=>u.Id==id);
            if (kitapTuruVt == null) { return NotFound(); }
            return View(kitapTuruVt);
        }

        [HttpPost]
        public IActionResult Guncelle(KitapTuru kitapTuru)
        {
            if (ModelState.IsValid)
            {
                _kitapTuruRepository.Guncelle(kitapTuru);
                _kitapTuruRepository.Kaydet(); //SaveChanges yapmazsanız bilgiler veritabanına eklenmez.
                TempData["basarili"] = "Kitap Türü Başarılıyla Güncellendi.";
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET ACTION
        public IActionResult Sil(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            KitapTuru? kitapTuruVt = _kitapTuruRepository.Get(u => u.Id == id);
            if (kitapTuruVt == null) { return NotFound(); }
            return View(kitapTuruVt);
        }

        [HttpPost, ActionName("Sil")]
        public IActionResult SilPOST(int? id)
        {
            KitapTuru? kitapTuru = _kitapTuruRepository.Get(u => u.Id == id);
            if (kitapTuru == null)
            {
                return NotFound(); 

                }
            _kitapTuruRepository.Sil(kitapTuru);
            _kitapTuruRepository.Kaydet();
            TempData["basarili"] = "Kitap Türü Başarılıyla Silindi.";
            return RedirectToAction("Index");
        }
    }
}

WebUygulamaProje1/Views/KitapTuru/Ekle.cshtml
@model KitapTuru

<form method="post">
    <div class="border p-3 mt-5">
        <div class="row pb-3">
      <h2 class="text-primary"> Kitap Türü Ekle</h2>
      </hr>
        </div>
<div class="mb-3">
        <label asp-for="Ad" class="p-0"></label>
        <input asp-for="Ad" class="form-control"/>
        <span asp-validation-for="Ad" class="text-danger"></span>

</div>

<button type="submit" class="btn btn-lg btn-primary" style="width:250px">Ekle</button>
        <a asp-controller="KitapTuru" asp-action="Index" class="btn btn-lg btn-primary" style="width:250px">
            Kitap Türlerine Geri Dön
        </a>
    </div> 

</form>

WebUygulamaProje1/Views/KitapTuru/Guncelle.cshtml
@model KitapTuru

<form method="post">
    <div class="border p-3 mt-5">
        <div class="row pb-3">
            <h2 class="text-primary"> Kitap Türü Güncelle</h2>
            </hr>
        </div>
        <div class="mb-3">
            <label asp-for="Ad" class="p-0"></label>
            <input asp-for="Ad" class="form-control" />
            <span asp-validation-for="Ad" class="text-danger"></span>

        </div>

        <button type="submit" class="btn btn-lg btn-primary" style="width:250px">Kitap Türü Güncelle</button>
        <a asp-controller="KitapTuru" asp-action="Index" class="btn btn-lg btn-primary" style="width:250px">
            Kitap Türlerine Geri Dön
        </a>
    </div>

</form>

WebUygulamaProje1/Views/KitapTuru/Index.cshtml
@model List<KitapTuru>

@if (TempData["basarili"] != null)
{
    <h2 style="color:red">@TempData["basarili"]</h2>

}

<div class="container">
    <div class="row pt-3 pb-4"
        <div>
<h1>Kitap Türü</h1>
</div></div>



    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
                <th>Kitap Türü</th>
                <th>

                </th>
                <th>

                </th>
            </tr>

        </thead>
        <tbody>
            @foreach (var kitapTuru in Model)
            {
                <tr>
                    <td>@kitapTuru.Id</td>
                    <td>@kitapTuru.Ad</td>
                    <td>
                        <a asp-controller="KitapTuru" asp-action="Guncelle" asp-route-id="@kitapTuru.Id" type="button" class="btn btn-success" style="width:250px">Güncelle</a>
                    </td>
                    <td>
                        <a asp-controller="KitapTuru" asp-action="Sil" asp-route-id="@kitapTuru.Id" type="button" class="btn btn-danger" style="width:250px">Sil</a>
                    </td>
                </tr>
            }
        </tbody>

    </table>
    <div class="row pt-3 pb-2">
        <div>
            <a asp-controller="KitapTuru" asp-action="Ekle" class="btn btn-lg btn-primary" type="button">
                Yeni Kitap Türü Oluştur
            </a>


        </div>
    </div>
</div>

WebUygulamaProje1/Views/KitapTuru/Sil.cshtml
@model KitapTuru

<form method="post">
    <input asp-for="Id" hidden/>
    <div class="border p-3 mt-5">
        <div class="row pb-3">
            <h2 class="text-primary"> Kitap Türü Sil</h2>
            </hr>
        </div>
        <div class="mb-3">
            <label asp-for="Ad" class="p-0"></label>
            <input asp-for="Ad" disabled class="form-control" />
           

        </div>

        <button type="submit" class="btn btn-lg btn-primary" style="width:250px">Sil</button>
        <a asp-controller="KitapTuru" asp-action="Index" class="btn btn-lg btn-primary" style="width:250px">
            Kitap Türlerine Geri Dön
        </a>
    </div>

</form>